productproductINSERT INTO producer (manhacungcap, tennhacungcap, sodienthoai, diachi) 
VALUES 
('ASUS', 'ASUS Technology', '0123456789', 'Taiwan'),
('LENOVO', 'Lenovo Group Ltd.', '0987654321', 'China'),
('DELL', 'Dell Technologies', '0345678912', 'USA'),
('HP', 'Hewlett-Packard', '0567891234', 'USA'),
('ACER', 'Acer Inc.', '0789123456', 'Taiwan');


INSERT INTO producer (manhacungcap, tennhacungcap, sodienthoai, diachi) 
VALUES ('APPLE', 'Apple Inc.', '0901234567', 'USA'),
('MSI', 'Micro-Star International', '0912345678', 'Taiwan');

DELETE FROM product;

-- Thêm 5 Laptop
INSERT INTO product (mamay, tenmay, soluong, gia, tenCPU, ram, xuatxu, cardmanhinh, mainboard, congsuatnguon, kichthuocman, dungluongpin, rom, loaimay, manhacungcap, dungluongluutru)
VALUES 
('LP1', 'Laptop Gaming ASUS ROG', 10, 25990000, 'Intel Core i7-12700H', '16GB', 'Việt Nam', 'NVIDIA RTX 3050', NULL, NULL, 15.6, '6-cell 80Wh', '512GB SSD', 'Laptop', 'NC001', 512),
('LP2', 'Laptop Dell XPS 15', 8, 32990000, 'Intel Core i9-12900HK', '32GB', 'Mỹ', 'NVIDIA RTX 3060', NULL, NULL, 15.6, '6-cell 97Wh', '1TB SSD', 'Laptop', 'NC002', 1024),
('LP3', 'Laptop HP Envy 13', 12, 18990000, 'Intel Core i5-1240P', '16GB', 'Nhật Bản', 'Intel Iris Xe', NULL, NULL, 13.3, '4-cell 65Wh', '512GB SSD', 'Laptop', 'NC003', 512),
('LP4', 'MacBook Pro 16', 6, 57990000, 'Apple M2 Max', '32GB', 'Mỹ', 'Apple M2 Max GPU', NULL, NULL, 16.0, '100Wh', '2TB SSD', 'Laptop', 'NC004', 2048),
('LP5', 'Acer Predator Helios 300', 15, 27990000, 'Intel Core i7-12650H', '16GB', 'Đài Loan', 'NVIDIA RTX 3070', NULL, NULL, 17.3, '4-cell 90Wh', '1TB SSD', 'Laptop', 'NC005', 1024);

-- Thêm 5 PC
INSERT INTO product (mamay, tenmay, soluong, gia, tenCPU, ram, xuatxu, cardmanhinh, mainboard, congsuatnguon, kichthuocman, dungluongpin, rom, loaimay, manhacungcap, dungluongluutru)
VALUES 
('PC1', 'PC Gaming MSI Aegis', 5, 40990000, 'Intel Core i9-13900K', '32GB', 'Mỹ', 'NVIDIA RTX 4090', 'MSI Z690', 850, NULL, NULL, '2TB SSD', 'PC', 'NC006', 2048),
('PC2', 'PC Workstation Dell Precision', 3, 52990000, 'Intel Xeon W-2235', '64GB', 'Mỹ', 'NVIDIA Quadro RTX 5000', 'Dell Precision T7920', 1000, NULL, NULL, '4TB SSD', 'PC', 'NC007', 4096),
('PC3', 'PC Văn phòng HP ProDesk', 10, 15990000, 'Intel Core i5-12400', '8GB', 'Nhật Bản', 'Intel UHD 730', 'HP ProDesk 400 G7', 300, NULL, NULL, '512GB SSD', 'PC', 'NC008', 512),
('PC4', 'PC Gaming Razer Tomahawk', 7, 37990000, 'Intel Core i7-13700KF', '32GB', 'Mỹ', 'NVIDIA RTX 3080 Ti', 'ASUS ROG Strix Z690', 750, NULL, NULL, '1TB SSD', 'PC', 'NC009', 1024),
('PC5', 'PC Đồ họa Mac Studio', 4, 65990000, 'Apple M1 Ultra', '128GB', 'Mỹ', 'Apple M1 Ultra GPU', 'Mac Studio Board', 350, NULL, NULL, '8TB SSD', 'PC', 'NC010', 8192);

-- Cập nhật nhà cung cấp theo mã máy mới
UPDATE product SET manhacungcap = 'ASUS' WHERE mamay IN ('LP1', 'PC4');
UPDATE product SET manhacungcap = 'DELL' WHERE mamay IN ('LP2', 'PC2');
UPDATE product SET manhacungcap = 'HP' WHERE mamay IN ('LP3', 'PC3');
UPDATE product SET manhacungcap = 'APPLE' WHERE mamay IN ('LP4', 'PC5');
UPDATE product SET manhacungcap = 'ACER' WHERE mamay IN ('LP5');
UPDATE product SET manhacungcap = 'MSI' WHERE mamay IN ('PC1');

CREATE TABLE country (
    id INT AUTO_INCREMENT PRIMARY KEY,
    maquocgia VARCHAR(3) NOT NULL UNIQUE,
    tenquocgia VARCHAR(100) NOT NULL
);


INSERT INTO country (maquocgia, tenquocgia) VALUES
('AF', 'Afghanistan'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AG', 'Antigua and Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BS', 'Bahamas'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BB', 'Barbados'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BZ', 'Belize'),
('BJ', 'Benin'),
('BT', 'Bhutan'),
('BO', 'Bolivia'),
('BA', 'Bosnia and Herzegovina'),
('BW', 'Botswana'),
('BR', 'Brazil'),
('BN', 'Brunei'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('CV', 'Cabo Verde'),
('KH', 'Cambodia'),
('CM', 'Cameroon'),
('CA', 'Canada'),
('CF', 'Central African Republic'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CO', 'Colombia'),
('KM', 'Comoros'),
('CG', 'Congo'),
('CR', 'Costa Rica'),
('HR', 'Croatia'),
('CU', 'Cuba'),
('CY', 'Cyprus'),
('CZ', 'Czech Republic'),
('CD', 'Democratic Republic of the Congo'),
('DK', 'Denmark'),
('DJ', 'Djibouti'),
('DM', 'Dominica'),
('DO', 'Dominican Republic'),
('EC', 'Ecuador'),
('EG', 'Egypt'),
('SV', 'El Salvador'),
('GQ', 'Equatorial Guinea'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('SZ', 'Eswatini'),
('ET', 'Ethiopia'),
('FJ', 'Fiji'),
('FI', 'Finland'),
('FR', 'France'),
('GA', 'Gabon'),
('GM', 'Gambia'),
('GE', 'Georgia'),
('DE', 'Germany'),
('GH', 'Ghana'),
('GR', 'Greece'),
('GD', 'Grenada'),
('GT', 'Guatemala'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haiti'),
('HN', 'Honduras'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Iran'),
('IQ', 'Iraq'),
('IE', 'Ireland'),
('IL', 'Israel'),
('IT', 'Italy'),
('JM', 'Jamaica'),
('JP', 'Japan'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KI', 'Kiribati'),
('KW', 'Kuwait'),
('KG', 'Kyrgyzstan'),
('LA', 'Laos'),
('LV', 'Latvia'),
('LB', 'Lebanon'),
('LS', 'Lesotho'),
('LR', 'Liberia'),
('LY', 'Libya'),
('LI', 'Liechtenstein'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malaysia'),
('MV', 'Maldives'),
('ML', 'Mali'),
('MT', 'Malta'),
('MH', 'Marshall Islands'),
('MR', 'Mauritania'),
('MU', 'Mauritius'),
('MX', 'Mexico'),
('FM', 'Micronesia'),
('MD', 'Moldova'),
('MC', 'Monaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MA', 'Morocco'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('NL', 'Netherlands'),
('NZ', 'New Zealand'),
('NI', 'Nicaragua'),
('NE', 'Niger'),
('NG', 'Nigeria'),
('KP', 'North Korea'),
('MK', 'North Macedonia'),
('NO', 'Norway'),
('OM', 'Oman'),
('PK', 'Pakistan'),
('PW', 'Palau'),
('PA', 'Panama'),
('PG', 'Papua New Guinea'),
('PY', 'Paraguay'),
('PE', 'Peru'),
('PH', 'Philippines'),
('PL', 'Poland'),
('PT', 'Portugal'),
('QA', 'Qatar'),
('RO', 'Romania'),
('RU', 'Russia'),
('RW', 'Rwanda'),
('KN', 'Saint Kitts and Nevis'),
('LC', 'Saint Lucia'),
('VC', 'Saint Vincent and the Grenadines'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Sao Tome and Principe'),
('SA', 'Saudi Arabia'),
('SN', 'Senegal'),
('RS', 'Serbia'),
('SC', 'Seychelles'),
('SL', 'Sierra Leone'),
('SG', 'Singapore'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('SB', 'Solomon Islands'),
('SO', 'Somalia'),
('ZA', 'South Africa'),
('KR', 'South Korea'),
('SS', 'South Sudan'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SD', 'Sudan'),
('SR', 'Suriname'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('SY', 'Syria'),
('TJ', 'Tajikistan'),
('TZ', 'Tanzania'),
('TH', 'Thailand'),
('TL', 'Timor-Leste'),
('TG', 'Togo'),
('TO', 'Tonga'),
('TT', 'Trinidad and Tobago'),
('TN', 'Tunisia'),
('TR', 'Turkey'),
('TM', 'Turkmenistan'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ukraine'),
('AE', 'United Arab Emirates'),
('GB', 'United Kingdom'),
('US', 'United States'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VU', 'Vanuatu'),
('VA', 'Vatican City'),
('VE', 'Venezuela'),
('VN', 'Vietnam'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe');

CREATE TABLE City (
    maquocgia VARCHAR(3) NOT NULL,
    mathanhpho VARCHAR(10) NOT NULL PRIMARY KEY,
    tenthanhpho VARCHAR(100) NOT NULL,
    FOREIGN KEY (maquocgia) REFERENCES country(maquocgia)
);

INSERT INTO City (maquocgia, mathanhpho, tenthanhpho) VALUES
('VN', '01', 'Hà Nội'),
('VN', '02', 'Hà Giang'),
('VN', '04', 'Cao Bằng'),
('VN', '06', 'Bắc Kạn'),
('VN', '08', 'Tuyên Quang'),
('VN', '10', 'Lào Cai'),
('VN', '11', 'Điện Biên'),
('VN', '12', 'Lai Châu'),
('VN', '14', 'Sơn La'),
('VN', '15', 'Yên Bái'),
('VN', '17', 'Hòa Bình'),
('VN', '19', 'Thái Nguyên'),
('VN', '20', 'Lạng Sơn'),
('VN', '22', 'Quảng Ninh'),
('VN', '24', 'Bắc Giang'),
('VN', '25', 'Phú Thọ'),
('VN', '26', 'Vĩnh Phúc'),
('VN', '27', 'Bắc Ninh'),
('VN', '30', 'Hải Dương'),
('VN', '31', 'Hải Phòng'),
('VN', '33', 'Hưng Yên'),
('VN', '34', 'Thái Bình'),
('VN', '35', 'Hà Nam'),
('VN', '36', 'Nam Định'),
('VN', '37', 'Ninh Bình'),
('VN', '38', 'Thanh Hóa'),
('VN', '40', 'Nghệ An'),
('VN', '42', 'Hà Tĩnh'),
('VN', '44', 'Quảng Bình'),
('VN', '45', 'Quảng Trị'),
('VN', '46', 'Thừa Thiên Huế'),
('VN', '48', 'Đà Nẵng'),
('VN', '49', 'Quảng Nam'),
('VN', '51', 'Quảng Ngãi'),
('VN', '52', 'Bình Định'),
('VN', '54', 'Phú Yên'),
('VN', '56', 'Khánh Hòa'),
('VN', '58', 'Ninh Thuận'),
('VN', '60', 'Bình Thuận'),
('VN', '62', 'Kon Tum'),
('VN', '64', 'Gia Lai'),
('VN', '66', 'Đắk Lắk'),
('VN', '67', 'Đắk Nông'),
('VN', '68', 'Lâm Đồng'),
('VN', '70', 'Bình Phước'),
('VN', '72', 'Tây Ninh'),
('VN', '74', 'Bình Dương'),
('VN', '75', 'Đồng Nai'),
('VN', '77', 'Bà Rịa - Vũng Tàu'),
('VN', '79', 'TP. Hồ Chí Minh'),
('VN', '80', 'Long An'),
('VN', '82', 'Tiền Giang'),
('VN', '83', 'Bến Tre'),
('VN', '84', 'Trà Vinh'),
('VN', '86', 'Vĩnh Long'),
('VN', '87', 'Đồng Tháp'),
('VN', '89', 'An Giang'),
('VN', '91', 'Kiên Giang'),
('VN', '92', 'Cần Thơ'),
('VN', '93', 'Hậu Giang'),
('VN', '94', 'Sóc Trăng'),
('VN', '95', 'Bạc Liêu'),
('VN', '96', 'Cà Mau');


CREATE TABLE District (
    mathanhpho VARCHAR(10) NOT NULL,
    maquan VARCHAR(10) NOT NULL,
    tenquan VARCHAR(100) NOT NULL,
    PRIMARY KEY (mathanhpho, maquan),
    FOREIGN KEY (mathanhpho) REFERENCES City(mathanhpho)
);
INSERT INTO District (mathanhpho, maquan, tenquan) VALUES
('48', '490', 'Hải Châu'),
('48', '491', 'Thanh Khê'),
('48', '492', 'Sơn Trà'),
('48', '493', 'Ngũ Hành Sơn'),
('48', '494', 'Liên Chiểu'),
('48', '495', 'Cẩm Lệ'),
('48', '497', 'Huyện Hòa Vang'),
('48', '498', 'Huyện Hoàng Sa');




UPDATE product SET manhacungcap = 'HP' WHERE mamay IN ('LAP003', 'PC003');
UPDATE product SET manhacungcap = 'APPLE' WHERE mamay IN ('LAP004', 'PC005');
UPDATE product SET manhacungcap = 'ACER' WHERE mamay IN ('LAP005');
UPDATE product SET manhacungcap = 'MSI' WHERE mamay IN ('PC001');
